{{- if .Values.otpki.loginPasswordKey }}
apiVersion: v1
kind: Secret
metadata:
  name: otpki-connector-secret
data:
  login_password_key: {{ .Values.otpki.loginPasswordKey | b64enc | quote }}
{{- end }}
