{{- $replicaCount := pluck "replicaCount" .Values.global .Values | compact | first }}
{{- $httpProxy := pluck "httpProxy" .Values.global .Values | compact | first }}
{{- $httpsProxy := pluck "httpsProxy" .Values.global .Values | compact | first }}
{{- $noProxy := pluck "noProxy" .Values.global .Values | compact | first }}
{{- $additionalInitContainers := (include "otpki-connector.customization.initContainers" $) }}
{{- $additionalSidecarContainers := (include "otpki-connector.customization.sidecarContainers" $) }}
{{- $additionalVolumes := (include "otpki-connector.customization.volumes" $) }}
{{- $additionalVolumeMounts := (include "otpki-connector.customization.volumeMounts" $) }}
{{- $additionalEnv := (include "otpki-connector.customization.env" $) }}
{{- $additionalEnvFrom := (include "otpki-connector.customization.envFrom" $) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otpki-connector-deployment
  labels:
    {{- include "otpki-connector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ $replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otpki-connector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otpki-connector.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
        # when the list of the trusted certificates is changed, restart deployment
        checksum/trusted-certificates-local: {{ include (print $.Template.BasePath "/trusted-certificates-secret.yaml") . | sha256sum }}
        {{- if .Values.global.trusted.certificates }}
        checksum/trusted-certificates-global: {{ include ("ilm-lib.trusted.certificates.secret.global") . | sha256sum }}
        {{- end }}
        {{- if .Values.otpki.loginPasswordKey }}
        # when the login password key changes, restart deployment
        checksum/secret: {{ include (print $.Template.BasePath "/otpki-connector-secret.yaml") . | sha256sum }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "otpki-connector.imagePullSecrets" . | indent 6 }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- .Values.podSecurityContext | toYaml | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "otpki-connector.serviceAccountName" . }}
      {{- if $additionalInitContainers }}
      initContainers:
        {{- $additionalInitContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: otpki-connector
          image: {{ include "otpki-connector.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.command }}
          command: {{- include "otpki-connector.image.command" . | nindent 12 }}
          {{- end }}
          {{- if .Values.image.args }}
          args: {{- include "otpki-connector.image.args" . | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.otel.serviceName | quote }}
            {{- if .Values.otel.exporterOtlpEndpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.otel.exporterOtlpEndpoint | quote }}
            {{- end }}
            {{- if ne (.Values.tracing.samplingProbability | toString) "" }}
            - name: TRACING_SAMPLING_PROBABILITY
              value: {{ .Values.tracing.samplingProbability | quote }}
            {{- end }}
            {{- if .Values.global.trusted.certificates }}
            - name: TRUSTED_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: trusted-certificates
                  key: ca.crt
            {{- else if .Values.trusted.certificates }}
            - name: TRUSTED_CERTIFICATES
              valueFrom:
                secretKeyRef:
                  name: trusted-certificates-{{ .Chart.Name | lower }}
                  key: ca.crt
            {{- end }}
            {{- if .Values.otpki.loginPasswordKey }}
            - name: OTPKI_LOGIN_PASSWORD_KEY
              valueFrom:
                secretKeyRef:
                  name: otpki-connector-secret
                  key: login_password_key
            {{- end }}
            {{- if $httpProxy }}
            - name: HTTP_PROXY
              value: {{ $httpProxy }}
            {{- end }}
            {{- if $httpsProxy }}
            - name: HTTPS_PROXY
              value: {{ $httpsProxy }}
            {{- end }}
            {{- if $noProxy }}
            - name: NO_PROXY
              value: {{ $noProxy }}
            {{- end }}
            {{- if $additionalEnv }}
              {{- $additionalEnv | nindent 12 }}
            {{- end }}
          {{- if $additionalEnvFrom }}
          envFrom:
            {{- $additionalEnvFrom | indent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.image.securityContext }}
          securityContext: {{- .Values.image.securityContext | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.image.probes.liveness.enabled }}
          livenessProbe:
            {{- if .Values.image.probes.liveness.custom }}
            {{- toYaml .Values.image.probes.liveness.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v2/health/liveness
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.liveness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.liveness.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.liveness.periodSeconds }}
            successThreshold: {{ .Values.image.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.image.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.image.probes.readiness.enabled }}
          readinessProbe:
            {{- if .Values.image.probes.readiness.custom }}
            {{- toYaml .Values.image.probes.readiness.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v2/health/readiness
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.readiness.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.readiness.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.readiness.periodSeconds }}
            successThreshold: {{ .Values.image.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.image.probes.readiness.failureThreshold }}
          {{- end }}
          {{- if .Values.image.probes.startup.enabled }}
          startupProbe:
            {{- if .Values.image.probes.startup.custom }}
            {{- toYaml .Values.image.probes.startup.custom | nindent 12 }}
            {{- else }}
            httpGet:
              path: /v2/health/liveness
              port: {{ .Values.service.port }}
            {{- end }}
            initialDelaySeconds: {{ .Values.image.probes.startup.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.image.probes.startup.timeoutSeconds }}
            periodSeconds: {{ .Values.image.probes.startup.periodSeconds }}
            successThreshold: {{ .Values.image.probes.startup.successThreshold }}
            failureThreshold: {{ .Values.image.probes.startup.failureThreshold }}
          {{- end }}
          {{- if .Values.image.resources }}
          resources: {{- toYaml .Values.image.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: ephemeral
            {{- if $additionalVolumeMounts }}
              {{- $additionalVolumeMounts | nindent 12 }}
            {{- end }}
        {{- if $additionalSidecarContainers }}
          {{- $additionalSidecarContainers | nindent 8 }}
        {{- end }}
      volumes:
        - name: ephemeral
          {{- include "otpki-connector.ephemeralVolume" . | indent 10 }}
        {{- if $additionalVolumes }}
          {{- $additionalVolumes | nindent 8 }}
        {{- end }}
